sonar.projectKey=CultivaSena-Sensores
sonar.projectName=CultivaSena Sensores

sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_8c2aa736c6644a0ce91259ac2867405d67136c13


sonar-scanner \
  -Dsonar.projectKey=CultivaSena-admin \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=sqp_abfc85f8bce1b7e91b163304f3ff265958e584d7